language:
- node_js
node_js:
- '6'
- '5'
- '4'
sudo: false
cache:
  directories:
  - node_modules
script:
- npm run fly
deploy:
  provider: npm
  email: log@logn.in
  api_key:
    secure: OE7VzHdjODijebjf0VfmKjRHeNvn6PWH3LCldIUSIE83eLqJYzMUUrawIQAEgGtuTPTIQXZZtxbrAGX7yc5ZimC7V9Bu4osKu9oxuKRR8LmvLq04eRxNXPZi1GsB6RGxs94uk8/iBvs1EmrEaF9pd7fEUcfx1XFJ3X596wCs5jxUaIc6+CphvpNdlwmqKkvThnKDzLMhWMSHcgQ8Puvs/dUzIG/eQQxdiQr5do5c5g19wZ/uzIQK7j+WqeOYOegQMJOlK/4Wfn1bsSfAzXgKtweBIqOKrPp66r/y7eq288g83KfIloOAc4BZ+klvh7mE6Ehf9t7Q1B1kjapqkSBllDeMgY7/iXVkIsFRtOXTPeXU370cAYNRICJdO1U76Ng2GEyhGyhfebaNsFg/mD47/qTgQdu9kA/LYfU+VBONtiyAJx/DgmfbLP3vjdbJqXW6sJ1yrGzYnfLPwZRUAibiXe6AZWv5f/FEDcV6vlAWNL9NMjfmCO0JXUILtmWYXwG5WUCrJn8k5LzVS72zJ1mj6KmSInfMddnhfZFJmp8F+H7+IwWo/z0NDx3SE8IfuJKI7oiA7lAn6leP9cXi1YcSUnHce4m2QPoeMf+NR9si5v5UKkodP2ytFfjq2B6MFmoEjyOG8zjiaFDakHJP/OizxHdyeBRThj0rE0wb4vCQMIE=
  on:
    tags: true
    repo: k-kinzal/fly-bin
  skip_cleanup: true
